### ISSUE TITLE
System with nic Intel I219-V not able to for from network  

### ISSUE THREAD

**Issue by noslin005** [grml/grml#153] opened 2020-07-16 03:18 UTC
Hi.
I work for a  company, where most of the systems are build and then tested using GRML.
We have a PXE server, that any machine should boot from, so we can run the test.
So far, GRML is being very important. But, sometimes we have problems where the system is not able to boot via network, because GRML netboot image is a missing module for the network card. 
The most recent problem I found is for systems that uses Intel i219-V nics.
I tried to add the driver to the 'initramfs', but I couldn't get it to work.
Is there a way we can remaster GRML to include new drivers for devices, like network cards, for example?

**Comment by mika** [comment] 2020-07-17 09:51
Are you using the latest Grml 2020.06 release? Do you know whether the driver for the Intel I219-V NIC is already included in any upstream kernel version? Is this supposed to be supported by the e1000e driver already or is this only available via https://downloadcenter.intel.com/de/product/82186 or alike?

With our netboot packages we also ship the e1000 + e1000e drivers, so it sounds like this driver either doesn't support the I219-V hardware (yet), a required firmware file might be missing or it's about another driver? Assuming that the e1000e driver is supposed to support it: do you have the `dmesg` output (and `lspci` and `lsmod` could be also useful) available of such a system?

If you want to include specific packages/files/...: remastering Grml can be done via [grml-live](https://grml.org/grml-live/), which allows you to customize the ISO just as needed. (I'm doing this for a bunch of customers who also have specific needs for their platforms similar to yours.)

**Comment by noslin005** [comment] 2020-07-17 14:31
Thank you @mika 
I'm using the Grml 2020.06. 
When I boot the system using Grml on USB, the network works good and the driver e100e is loaded fine. 

The only problem is when I boot it of PXE, the system can't boot because it fails to mount the NFS share with Grml. 

The driver is e100e as you mentioned
Please see below some screenshots:

![image](https://user-images.githubusercontent.com/1957756/87796211-0b715080-c817-11ea-865a-aaf9871bef10.png)

![image](https://user-images.githubusercontent.com/1957756/87796975-18db0a80-c818-11ea-85a2-bb7a1648025f.png)

![image](https://user-images.githubusercontent.com/1957756/87797166-5475d480-c818-11ea-89aa-550ec60411d6.png)

![image](https://user-images.githubusercontent.com/1957756/87797292-7707ed80-c818-11ea-890b-39dffc668c72.png)

**Comment by mika** [comment] 2020-07-17 15:02
@noslin005 hm, given that `eth0` is present though: is `1c:69:7a:66:b4:58` corresponding to the Intel I219-V NIC? What's the output of `dmesg`? What's the output of `cat /netboot-eth0.config`? Does a manual invocation of `ipconfig -t 15 eth0` fail as well? The corresponding DHCP server is available/reachable for sure?

**Comment by noslin005** [comment] 2020-07-17 19:46
@mika I can't get the output of the `dmesg` because I don't have network access in order to copy it and send it to you. Right now I can only take pictures.

`cat /netboot-eth0.config`
![image](https://user-images.githubusercontent.com/1957756/87825063-6d947a80-c844-11ea-8cfe-4819a89342eb.png)

`ipconfig -t 15 eth0` says:

```bash
ifconfig: SIOSCIFADDR: No such device
```

**Comment by mika** [comment] 2020-07-17 19:55
@noslin005 I'm perfectly fine with a screenshot/picture of `dmesg` output (only the last page should matter, where the network driver(s) get loaded!)

The `ifconfig: SIOSCIFADDR: No such device` for the  `ipconfig -t 15 eth0` sounds strange, it's like `eth0` wouldn't exist, hmmmm

**Comment by noslin005** [comment] 2020-07-17 20:13
Here's part of the dmesg. 
![IMG_20200717_161006__01](https://user-images.githubusercontent.com/1957756/87827106-26a88400-c848-11ea-81ee-54bdd726cd65.jpg)
![IMG_20200717_161148__01](https://user-images.githubusercontent.com/1957756/87827167-4b046080-c848-11ea-8be8-2125b627dc54.jpg)

**Comment by mika** [comment] 2020-07-17 20:26
Alright, nothing suspicious regarding the `e1000e` driver present here. :-/

Is there anything new in `dmesg` output visible once the `ipconfig -t ...` finished its execution?
I'd assume the driver is disabling the device or so, given the error message you provided earlier.
Does it always fail for you when manually executing `ipconfig -t 15 eth0` then?

Could you boot this system via USB/DVD on this system to check its networking state from the running user space (where ethtool and more tools are available for further debugging)?

For me it sounds like what other folks are reporting in e.g. https://bugzilla.kernel.org/show_bug.cgi?id=205047, https://forum.proxmox.com/threads/e1000-driver-hang.58284/page-5 + https://bugzilla.kernel.org/show_bug.cgi?id=205047

Is this an Intel NUC? Did you try to update the NIC's firmware already?

(If nothing of this provides useful information, I'd suggest to run tcpdump or alike on the DHCP server side, to see whether there's any traffic visible from this client at all.)

**Comment by noslin005** [comment] 2020-07-17 21:01
@mika I don't see any other output in the `dmsg` about `ifconfig` that can help
yes, the command `ipconfig -t 15 eth0` always fail.

Yes, it's a NUC, and the firmware is updated. When I boot off a USB The network works fine.
We have these issues with other systems that use the same network device i219-V.

**Comment by mika** [comment] 2020-07-17 21:28
Uff ok, so I'd assume that either klibc-utils's `ipconfig` triggers a bug, the e1000e of the 5.6 kernel has a bug, something™ is missing in the initramfs we're not aware of, or....

It might be worth trying to reduce the gigabit to 100mbit or disable auto-negotiation. (That's related to what users in https://bugzilla.kernel.org/show_bug.cgi?id=205047 reported.) I just pushed https://github.com/grml/live-boot-grml/commit/b1e38b17b735400efe701076f95c5950aa0f7dfc so we have `ethtool` available in initramfs stage. 

Our [daily ISOs](https://grml.org/daily/) also already include kernel 5.7, that might be worth another try. (In linux's git I see changes related to e1000e that are scheduled for 5.8, though I'm not sure they are really relevant for you.)

In a few hours (around 7-8 hours from now) we should have fresh daily ISOs which include the `ethtool` in the initramfs, that might be worth a try then.

**Comment by mika** [comment] 2020-07-18 10:04
FTR, the builds from https://daily.grml.org include the change by now.

**Comment by noslin005** [comment] 2020-07-18 17:22
I'll try it Monday, and let you know. I appreciate for your quick support.

**Comment by mika** [comment] 2020-07-19 12:00
BTW, I just had a related issue with the `e1000e` driver where setting kernel option `ethdevice-timeout=30` helped in booting it:

![e1000e](https://user-images.githubusercontent.com/115592/87874181-1a4b3500-c9c8-11ea-9438-02244e424392.jpg)

But on this system a manual `ipconfig -t 15 eth0` run from the failing initramfs stage resulted in a working network link, so this *might* be different for you.

**Comment by noslin005** [comment] 2020-07-20 16:25
@mika Thanks for your help. 
Setting the `ethdevice-timeout=30` solved the problem. I tested it on both Grml 2020.06 and the latest daily build as of today.
I guess I'll add this parameter as default on the Grml Pxe Menu. 
I really appreciate for the time you took to help me solve this issue.

**Comment by mika** [comment] 2020-07-20 16:35
Excellent and glad to hear it works for you!

So it seems to be related to the e1000/e1000e driver issue I could also notice, once I can confirm that it's really related to the driver/kernel versions I'll open a separate issue, I'm closing this issue hereby.

**Closed by mika** 2020-07-20 16:35 UTC
