### ISSUE TITLE
isolinux.bin missing or corrupt

### ISSUE THREAD

**Issue by suntong** [grml/grml#182] opened 2021-10-16 20:33 UTC
**Describe the bug**
I got `isolinux.bin missing or corrupt` after `dd` `grml64-full_2021.07.iso` to my usb, partition 3, and boot from it.

**Steps To Reproduce**

```
$ fdisk -l /dev/sdf
Disk /dev/sdf: 14.53 GiB, 15606349824 bytes, 30481152 sectors
Disk model: DataTraveler 109
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0xb658f34c

Device     Boot    Start      End  Sectors  Size Id Type
/dev/sdf1           2048 12290047 12288000  5.9G 83 Linux
/dev/sdf2       12290048 22530047 10240000  4.9G 83 Linux
/dev/sdf3  *    22530048 24627199  2097152    1G  c W95 FAT32 (LBA)
/dev/sdf4       24627200 30481151  5853952  2.8G 83 Linux

$ sha256sum --ignore-missing -c SHA256SUMS
grml64-full_2021.07.iso: OK

$ sudo dd if=grml64-full_2021.07.iso of=/dev/sdf3
1610240+0 records in
1610240+0 records out
824442880 bytes (824 MB, 786 MiB) copied, 323.895 s, 2.5 MB/s
```

Then boot from it.

**Expected behavior**

Grml will be able to boot from usb-stick.

**Additional context**

The same partition, /dev/sdf3, was holding grml64-full_2020.06.iso before, `dd`ed the same way, and it was bootable before.

**Comment by mika** [comment] 2021-10-18 06:17
You have to `dd` the ISO to the main device (`/dev/sdX`), and not towards an arbitrary partition (like `/dev/sdX3`).
If the problem is still reproducible, then please let us know and we can investigate further, until then I'm closing this issue though. :)

**Closed by mika** 2021-10-18 06:17 UTC
Labels: moreinfo
