### ISSUE TITLE
grml64-full 2017.05: VNC server does not start

### ISSUE THREAD

**Issue by sl0n** [grml/grml#79] opened 2017-11-06 15:05 UTC
I tried to add the following (extra) flags to start VNC server, however don't see it actually running:

ssh=mypasswd vnc=mypasswd startx

X server starts OK though.

Any ideas?

```
root@grml ~ # ps -ef | grep X
grml      2189  2167  0 15:02 tty7     00:00:00 xinit /home/grml/.xinitrc -- /etc/X11/xinit/xserverrc :0 vt7 -keeptty -auth /tmp/serverauth.j1n49uCO2q
grml      2190  2189  2 15:02 tty7     00:00:01 /usr/lib/xorg/Xorg -nolisten tcp :0 vt7 -keeptty -auth /tmp/serverauth.j1n49uCO2q
root      2303  2232  0 15:04 pts/0    00:00:00 grep --color=auto X
root@grml ~ # 
root@grml ~ # 
root@grml ~ # ps -ef | grep -i vnc
root      2336  2232  0 15:04 pts/0    00:00:00 grep --color=auto -i vnc
root@grml ~ # 
root@grml ~ # 
root@grml ~ # netstat -na
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN     
tcp        0    580 10.0.0.170:22           10.10.0.6:32994         ESTABLISHED
tcp6       0      0 :::22                   :::*                    LISTEN     
udp        0      0 0.0.0.0:68              0.0.0.0:*                          
Active UNIX domain sockets (servers and established)
Proto RefCnt Flags       Type       State         I-Node   Path
unix  8      [ ]         DGRAM                    14848    /run/systemd/journal/dev-log
unix  2      [ ]         DGRAM                    21007    /run/user/1000/systemd/notify
unix  2      [ ACC ]     STREAM     LISTENING     21267    /dev/gpmctl
unix  2      [ ACC ]     STREAM     LISTENING     21011    /run/user/1000/systemd/private
unix  2      [ ACC ]     STREAM     LISTENING     21476    @/tmp/.X11-unix/X0
unix  2      [ ACC ]     STREAM     LISTENING     21041    /run/user/1000/gnupg/S.gpg-agent.browser
unix  2      [ ACC ]     STREAM     LISTENING     21044    /run/user/1000/gnupg/S.gpg-agent.ssh
unix  2      [ ACC ]     STREAM     LISTENING     21046    /run/user/1000/gnupg/S.gpg-agent
unix  2      [ ACC ]     STREAM     LISTENING     21048    /run/user/1000/gnupg/S.gpg-agent.extra
unix  2      [ ]         DGRAM                    22113    /run/user/0/systemd/notify
unix  2      [ ACC ]     STREAM     LISTENING     22117    /run/user/0/systemd/private
unix  2      [ ACC ]     STREAM     LISTENING     22122    /run/user/0/gnupg/S.gpg-agent.ssh
unix  2      [ ACC ]     STREAM     LISTENING     22125    /run/user/0/gnupg/S.gpg-agent.extra
unix  2      [ ACC ]     STREAM     LISTENING     22127    /run/user/0/gnupg/S.gpg-agent
unix  2      [ ACC ]     STREAM     LISTENING     22129    /run/user/0/gnupg/S.gpg-agent.browser
unix  2      [ ]         DGRAM                    18042    /run/systemd/journal/syslog
unix  2      [ ACC ]     STREAM     LISTENING     22143    /tmp/ssh-n3aRptrKkA/agent.2223
unix  3      [ ]         DGRAM                    14812    /run/systemd/notify
unix  2      [ ]         DGRAM                    14814    /run/systemd/cgroups-agent
unix  2      [ ACC ]     STREAM     LISTENING     14818    /run/systemd/private
unix  2      [ ACC ]     STREAM     LISTENING     21477    /tmp/.X11-unix/X0
unix  2      [ ACC ]     STREAM     LISTENING     16367    /var/run/dbus/system_bus_socket
unix  2      [ ACC ]     STREAM     LISTENING     14839    /run/systemd/journal/stdout
unix  7      [ ]         DGRAM                    14842    /run/systemd/journal/socket
unix  2      [ ACC ]     SEQPACKET  LISTENING     14845    /run/udev/control
unix  3      [ ]         STREAM     CONNECTED     16853    /run/systemd/journal/stdout
unix  2      [ ]         DGRAM                    15820    
unix  3      [ ]         STREAM     CONNECTED     17066    
unix  3      [ ]         STREAM     CONNECTED     16807    
unix  3      [ ]         STREAM     CONNECTED     17069    /var/run/dbus/system_bus_socket
unix  2      [ ]         DGRAM                    15868    
unix  2      [ ]         DGRAM                    20981    
unix  3      [ ]         STREAM     CONNECTED     16804    
unix  2      [ ]         DGRAM                    20963    
unix  3      [ ]         STREAM     CONNECTED     20952    /run/systemd/journal/stdout
unix  2      [ ]         DGRAM                    19533    
unix  3      [ ]         STREAM     CONNECTED     16494    
unix  3      [ ]         DGRAM                    14816    
unix  3      [ ]         STREAM     CONNECTED     21611    @/tmp/.X11-unix/X0
unix  2      [ ]         DGRAM                    20864    
unix  3      [ ]         STREAM     CONNECTED     21768    @/tmp/.X11-unix/X0
unix  3      [ ]         STREAM     CONNECTED     15744    
unix  3      [ ]         STREAM     CONNECTED     15918    /run/systemd/journal/stdout
unix  3      [ ]         DGRAM                    16355    
unix  2      [ ]         DGRAM                    20725    
unix  3      [ ]         STREAM     CONNECTED     20951    
unix  2      [ ]         DGRAM                    19024    
unix  3      [ ]         STREAM     CONNECTED     21493    
unix  3      [ ]         STREAM     CONNECTED     20612    /run/systemd/journal/stdout
unix  2      [ ]         DGRAM                    15216    
unix  3      [ ]         STREAM     CONNECTED     21767    
unix  3      [ ]         DGRAM                    21009    
unix  3      [ ]         STREAM     CONNECTED     21610    
unix  3      [ ]         STREAM     CONNECTED     20611    
unix  3      [ ]         DGRAM                    14817    
unix  3      [ ]         STREAM     CONNECTED     17067    
unix  2      [ ]         DGRAM                    16708    
unix  3      [ ]         STREAM     CONNECTED     17068    /var/run/dbus/system_bus_socket
unix  3      [ ]         STREAM     CONNECTED     16495    /run/systemd/journal/stdout
unix  3      [ ]         DGRAM                    21010    
unix  2      [ ]         DGRAM                    22104    
unix  2      [ ]         DGRAM                    22094    
unix  3      [ ]         STREAM     CONNECTED     21494    /var/run/dbus/system_bus_socket
unix  3      [ ]         DGRAM                    16356    
unix  3      [ ]         STREAM     CONNECTED     16852    
unix  2      [ ]         DGRAM                    22020    
unix  3      [ ]         STREAM     CONNECTED     22084    
unix  3      [ ]         STREAM     CONNECTED     22085    /run/systemd/journal/stdout
unix  3      [ ]         DGRAM                    22115    
unix  3      [ ]         DGRAM                    22116    

```

**Comment by jkirk** [comment] 2017-11-06 16:10
Thank you for your report. This is because `x11vnc` is missing in Grml 2017.05. This should be fixed in the current daily ISO.

Duplicate of #62. Closing.

**Closed by jkirk** 2017-11-06 16:10 UTC
