### ISSUE TITLE
verify boot menu options

### ISSUE THREAD

**Issue by mika** [grml/grml#10] opened 2017-01-27 14:58 UTC
grml-live's templates for the boot menu inside isolinux + grub needs to be verified if everything still works as intended (esp. with our switch to systemd).

**Comment by jkirk** [comment] 2017-05-31 13:55
Let's start simple. This is the isolinux boot menu:

- [x] grml-release (default)
- [x] Boot options for grml-release (submenu)
  - [x] Back to main menu...
  - [ ] Debug Mode
  - [ ] Disable Framebuffer
  - [ ] Enable SSH (with random
  - [ ] Forensic Mode
  - [ ] German Settings
  - [ ] Graphical Mode
  - [ ] Load to RAM
  - [ ] Persistency mode
  - [ ] Serial Console
- [x] Addons (submenu)
  - [x] Bootloader Grub2
  - [x] All-in-One-Image
  - [ ] iPXE
  - [ ] Netboot.xyz
  - [ ] FreeDos
  - [x] Memtest86+
  - [x] Hardware Detection Tool
- [x] Isolinux prompt
- [ ] Boot from next boot device

@mika: is there an official documentation for each entry so I know what "works as intended" really means.. ;-)

**Comment by jkirk** [comment] 2017-05-31 14:03
And this is the grub2 boot menu:

- [x] grml-release (default)
- [x] advanced options
  - [ ] enable persistency mode
  - [ ] copy Grml to RAM
  - [ ] copy whole medium to RAM
  - [ ] start X by default
  - [ ] disable framebuffer
  - [ ] disable Kernel Mode-Settin (*)
  - [ ] forensic mode
  - [ ] debug mode
  - [ ] serial mode
- [x] Addons (submenu)
  - [x] Memory test (memtest86+)
  - [ ] iPXE
  - [ ] Netboot.xyz
  - [ ] GRUB - all in one image
  - [ ] FreeDos
  - [ ] MirOS bsd4grml (via loopback)
- [ ] Boot from next boot device

(*) the entry is cut (at least on my VM).

**Comment by jkirk** [comment] 2018-12-23 03:46
Boot option `Debug Mode` is unclear:

[grml-cheatcodes.txt](https://github.com/grml/grml-live/blob/master/templates/GRML/grml-cheatcodes.txt) states:
```
debug                               Get shells during process of booting for debugging
[...]
grml debug                          Get shells during process of booting, using GNU screen, be verbose
grml debug=1                        Get shells during process of booting, using GNU screen, be verbose and
                                    display shell code being executed in initramfs.
grml debug=noscreen                 Get shells during process of booting, verbose, but without using GNU screen
```
and [isolinux/f3](https://github.com/grml/grml-live/blob/master/templates/boot/isolinux/f3) says:
```
debug [ break=live-bottom ]    get interactive shells during startup process
```
What is the expected behavior of each of these options? The boot process seems to be more verbose but not at the same level for each option. And what about the _shells during process of booting_? What is meant by that? And `break=live-bottom` does not to have any effect.

**Comment by jkirk** [comment] 2018-12-23 13:16
@Mika: And one more questions: Which order do you prefer? I would then work on a PR to bring the boot entries of Isolinux and Grub2 in line.

**Comment by mika** [comment] 2018-12-24 10:00
@jkirk IIRC we dropped the GNU screen sessions during bootup when we switched to systemd? The "debug" (without `grml` in its front) is relevant only for isolinux and _not_ GRUB. The `break=live-bottom` *should* work, unsure why it doesn't. Maybe live-boot changed there something once again, this _could_ be `break=live-realpremount` giving it a short look at the code. We'd have to verify this in more detail.
I'm not sure what you mean regarding the order. :)

**Comment by jkirk** [comment] 2021-07-21 11:53
Regarding the order:

For isolinux the `Boot options for grml64-full` look like this:
```
❯ grep menuentry templates/boot/grub/%SHORT_NAME%_options.cfg
menuentry "%GRML_NAME% - enable Predictable Network Interface Names" {
menuentry "%GRML_NAME% - enable persistency mode" {
menuentry "%GRML_NAME% - copy Grml to RAM" {
menuentry "%GRML_NAME% - copy whole medium to RAM" {
menuentry "%GRML_NAME% - start X by default" {
menuentry "%GRML_NAME% - disable framebuffer" {
menuentry "%GRML_NAME% - disable Kernel Mode-Setting" {
menuentry "%GRML_NAME% - forensic mode" {
menuentry "%GRML_NAME% - debug mode" {
menuentry "%GRML_NAME% - serial mode" {
```
For Grub the `grml64 - advanced options` look like this:
```
❯ grep "menu label" templates/boot/isolinux/grml.cfg
  menu label %GRML_NAME% - ^Debug Mode
  menu label %GRML_NAME% - Enable Predictable ^Network Interface Names
  menu label %GRML_NAME% - Dis^able Framebuffer
  menu label %GRML_NAME% - Disable ^Kernel Mode-Setting
  menu label %GRML_NAME% - Enable ^SSH (with random password)
  menu label %GRML_NAME% - F^orensic Mode
  menu label %GRML_NAME% - ^German Settings
  menu label %GRML_NAME% - Graphical ^Mode
  menu label %GRML_NAME% - Load to ^RAM
  menu label %GRML_NAME% - ^Persistency mode
  menu label %GRML_NAME% - Serial ^Console
```

The sub-menu entry ( `grml64 - advanced options` vs `Boot options for grml64-full`) and their entries a labeled differently and are in different order. I'd like to harmonize the entries, review the kernel options, check if they still work as expected and check/update the documentation/cheat-sheet.

So which naming and order do we prefer? (Either choose one (isolinux vs Grub order) or come up with a new order?)

I will also check the [hidden](https://github.com/grml/grml-live/blob/master/templates/boot/isolinux/hidden.cfg) isolinux entries, but for now lets stick to the "visible" options.

**Comment by jkirk** [comment] 2022-06-03 14:10
Checked the boot options 'Debug Mode' (once again) and following need to be done:

- [ ] move `menu label %GRML_NAME% - ^Debug Mode` above `menu label %GRML_NAME% - Serial ^Console`
- [ ] change case of `menuentry "%GRML_NAME% - debug mode" {` (-> `Debug Mode`)
- [ ] `Get shells during process of booting for debugging` in [grml-cheatcodes.txt](https://github.com/grml/grml-live/blob/master/templates/GRML/grml-cheatcodes.txt#L20) + [isolinux/f3](https://github.com/grml/grml-live/blob/master/templates/boot/isolinux/f3) is not true anymore (since: grml/grml-autoconfig@f9648a3663). Update the description.
- [ ] `http://git.grml.org/?p=live-initramfs-grml.git;a=blob_plain;f=manpages/live-initramfs.en.7.txt;hb=HEAD` link in [grml-cheatcodes.txt](https://github.com/grml/grml-live/blob/master/templates/GRML/grml-cheatcodes.txt#L28) is obsolete, not? Remove / update the line.
- [ ] What is difference between the Isolinux bootprompt options `debug` and `grml debug`? Clarify in [grml-cheatcodes.txt](https://github.com/grml/grml-live/blob/master/templates/GRML/grml-cheatcodes.txt#L148).
- [ ] Document kernel command line parameter `break`, see: [initramfs-tools(5)](https://manpages.debian.org/bullseye/initramfs-tools-core/initramfs-tools.7.en.html#break) and update [isolinux/f3](https://github.com/grml/grml-live/blob/master/templates/boot/isolinux/f3).
- [ ] Document the used kernel options / command line parameters:

https://github.com/grml/grml-live/blob/master/templates/boot/grub/%25SHORT_NAME%25_options.cfg:
```
  apm=power-off boot=live live-media-path=/live/%GRML_NAME%/ bootid=%BOOTID% nomce net.ifnames=0
  "${loopback}" ${kernelopts} initcall verbose debug=vc systemd.log_level=debug
  systemd.log_target=kmsg log_buf_len=1M
```
[isolinux/grml.cfg](https://github.com/grml/grml-live/blob/master/templates/boot/isolinux/grml.cfg):
```
  append initrd=/boot/%SHORT_NAME%/initrd.img boot=live live-media-path=/live/%GRML_NAME%/
  bootid=%BOOTID% apm=power-off vga=791 verbose debug=vc initcall nomce net.ifnames=0
  systemd.log_level=debug systemd.log_target=kmsg log_buf_len=1M
```

**Comment by jkirk** [comment] 2023-07-07 17:36
I propose the following order + naming for the "Advanced Options" of the Isolinux and Grub menu entries:

Advanced Options (submenu) [instead of Boot options for grml-release (submenu)  / advanced options ] ->

- Enable SSH (with random password) [missing in Grub menu]
- Load Grml to RAM [instead "Load to RAM" / "copy Grml to RAM"]
- Forensic Mode
- Persistency Mode [instead "Persistence mode" / "enable persistency mode"]
- German Keyboard Layout [instead "German Settings"] (*)
- Graphical Mode (grml-x)
- Disable Framebuffer
- Debug Mode
- Serial Console

(*) I am not sure yet, what German Settings actually does? In my latest Grml the keyboard layout was changed to German.

@mika any objections?

**Comment by mika** [comment] 2023-10-19 16:13
@jkirk FTR, I'm totally for unify the boot menu, more than happy to look into this together with you :)

**Comment by jkirk** [comment] 2023-11-17 18:08
@mika: What is the difference between "copy Grml to RAM" and "copy whole medium to RAM" in the Grub menu?

See:

https://github.com/grml/grml-live/blob/master/templates/boot/grub/%25SHORT_NAME%25_options.cfg#L18

https://github.com/grml/grml-live/blob/master/templates/boot/grub/%25SHORT_NAME%25_options.cfg#L26

And: I also need to review "Shortcut keys of vesamenu bootsplash" in

https://github.com/grml/grml-live/blob/892768a58e0962d6338d9d5bbd3c7cd7fcdfd77c/templates/boot/isolinux/isolinux.cfg#L34

**Comment by jkirk** [comment] 2023-12-07 16:26
Tested the isolinux boot options with the latest Grml daily (grml64-full_sid build4367, 2023-12-07):

- [x] grml-release (default)
- [x] Boot options for grml-release (submenu)
  - [x] Back to main menu...
  - [x] Enable Predictable Network Interface Names
  - [x] Load Grml to RAM
  - [x] Load whole medium to RAM --> Description too long
  - [x] Forensic Mode
  - [x] Persistency mode --> boots successfully, needs testing
  - [x] German Settings --> loads German Keyboard Layout
  - [x] Graphical Mode
  - [x] Disable Framebuffer
  - [x] Disable Kernel Mode-Setting --> Disable Kernel Mode Setting for various video drivers
  - [x] Debug Mode
  - [x] Enable SSH (with random password)
  - [x] Serial Console --> boots successfully, needs testing
- [x] Addons (submenu)
  - [x] Back to main menu...
  - [x] Bootloader Grub2
  - [x] All-in-One-Image
  - [x] iPXE --> needs testing
  - [x] Netboot.xyz --> needs testing
  - [x] FreeDos
  - [x] Memtest86+
  - [x] Hardware Detection Tool
- [x] Isolinux prompt
- [ ] Boot from next boot device

The boot options seem to work. The order has been unified. 

Final tasks to close this issue:
- [ ] remove the Grml release name from the boot options as it limits the title length.
- [ ] change "Disable Kernel Mode-Setting" -> "Disable Kernel Mode Setting for various video drivers"
- [ ] change "German Settings" -> "Load German Keyboard Layout"

@mika: We need to define an official documentation (location) for each boot option entry, so that the user (and I) know what the options are supposed to do and how to use them. We currently have:
- Cheatcodes: http://grml.org/cheatcodes/
- isolinux help (f1 .. f10): https://github.com/grml/grml-live/tree/master/templates/boot/isolinux

They are good starting points but I think we should do better. Do you have a 'documentation project' in mind that we can borrow from?

**Comment by jkirk** [comment] 2023-12-07 16:55
JFTR, "Disable Framebuffer" also disables Kernel Mode Setting and Graphical Mode (X11) does not work without KMS.

**Closed** 2023-12-22 15:54 UTC
Labels: verify
