### ISSUE TITLE
cosmetic output issues of grml 2017.05 RC on Dell Hardware

### ISSUE THREAD

**Issue by Zugschlus** [grml/grml#23] opened 2017-05-09 11:12 UTC
Hi,
a Dell PowerEdge R630 happily continues booting after the grml menu has been already printed. Additionally, a systemd startup message is printed earlier in the boot process. Both issues do not appear when booting inside VMware.
See attachments.
Greetings
Marc
![screenshot_20170509_130646](https://cloud.githubusercontent.com/assets/1712376/25848088/129adb28-34b9-11e7-9125-9aa460de5999.png)
![screenshot_20170509_130719](https://cloud.githubusercontent.com/assets/1712376/25848096/18c58818-34b9-11e7-91c4-557d5fa5f06e.png)

**Comment by mika** [comment] 2017-05-09 11:16
Thanks for reporting, this is https://github.com/grml/grml/issues/19

**Comment by mika** [comment] 2017-05-10 13:49
Closing, this is a duplicate of #19

**Closed by mika** 2017-05-10 13:49 UTC
