### ISSUE TITLE
ncurses graphics are broken in tmux

### ISSUE THREAD

**Issue by novoid** [grml/grml#186] opened 2021-11-06 19:21 UTC
**Describe the bug**

When I boot grml 2021-07 full and start a tmux session in text mode, ncurses tools like grml-debootstrap do have weird characters instead of the graphical elements such as lines.

**Steps To Reproduce**

- boot grml 2021-07 full 
- exit grml-quickconfig
- start tmux
- start grml-debootstrap (or other ncurses tool)

**Expected behavior**
I expect ncurses to show a normal interface with graphical text-elements such as lines.

**Screenshots**
I can provide a screenshot if this is necessary.

**In which Grml Version did the bug occur?**
grml 2021-07 full amd64

Output of `grml-version`:
```sh
grml64-full 2021.07 Release Codename JauKerl [2021-07-25]
...
```

**Comment by novoid** [comment] 2021-11-07 10:08
The issue is not present when accessing a grml system via ssh.

Steps to reproduce:

- grml
  - sudo ifconfig eth0 192.168.0.2 up
  - Start ssh
  - sudo passwd grml
- other Linux box
  - ssh grml@192.168.0.2
  - tmux
  - grml-quickconfig   -> ncurses looks fine

**Comment by jkirk** [comment] 2022-03-04 23:36
I just tried to reproduce this issue (running Grml 2021.07 in VirtualBox) and was not able to reproduce the problem:

![grml-debootstrap](https://user-images.githubusercontent.com/288637/156855947-2c25a894-7458-46a8-ad59-7242558bc845.gif)

Is this still an issue for you?

**Comment by mika** [comment] 2022-03-25 15:11
I can't reproduce the issue either :-/ I seem to recall that sometimes™ there are UTF8 issues on tty1, but I can't reproduce it.
@novoid if you should be aware of any ways how to reproduce your issue please let us know, so we can reopen this issue and investigate! For the time being I'll close the issue, thanks for taking care of providing us a bug report!

**Closed by mika** 2022-03-25 15:11 UTC

**Comment by novoid** [comment] 2022-03-26 17:21
I can't reproduce the issue with the identical USB thumb drive on a lenovo T490 (and not the original Ryzen machine from above).

If I'm able to reproduce the issue on the Ryzen system some day, I'll reopen here. Until then: thanks for the support :+1:
