### ISSUE TITLE
[FR] Add cloud-init to base

### ISSUE THREAD

**Issue by aenertia** [grml/grml#124] opened 2019-01-14 22:16 UTC
In cloud environment testing and validation especially with Openstack. GRML is incredibly useful as a small full featured distro for performance testing/debug/familiarization and other teaching and learning activities.

However it would be even better if cloud-init scripts were included in the base boot image and process allowing for ssh/user pass and other configuration information to be included during boot.

This is a Feature request/discussion about adding cloud-init support to the base GRML images.

What are others thoughts?

**Comment by mika** [comment] 2019-01-15 10:20
This sounds interesting! I know cloud-init from AWS environments and since we already have a ssh/user pass boot option support in Grml (see http://grml.org/cheatcodes/) I'd be interested to know, if there would be any further gains by integrating cloud-init into Grml.

@aenertia are you aware of any specific features that cloud-init would provide that Grml does _not_ provide yet? Do you have setup/any configuration examples for me, so I could try to reproduce such a setup? (I think what would be supported then are ssh *keys* and network configuration?)

**Comment by aenertia** [comment] 2019-02-08 20:59
sorry got swallowed in my email;

yeah there are a heap of things - ssh-key generation and injection is the main one. Being able to pull additional repo/installer bootstrap data from $whatever config management system you like (ansible, puppet, foreman etc).

NIC configuration

Arbitary script running

Cloud init is pretty useful, my main usecase is being able to drop in grml in place of cirros which is the defacto test vm image for open-stack. Metadata injection via provisioned cloud-init is essential for this

**Comment by mika** [comment] 2019-02-08 21:19
@aenertia that sounds definitely useful and worth consideration, I'll try to look into this and will keep you in the loop. Thanks for your feedback!

**Comment by mika** [comment] 2020-04-01 16:08
I just added cloud-init to grml-full, the daily ISOs as of tomorrow (2020-04-02) should include it. Testing it via `services=cloud-init` should be possible then, once we know that this works as intended we could consider adding it to grml-small as well. (To verify/discuss: whether to enable cloud-init by default)

**Comment by mika** [comment] 2020-04-01 16:21
FTR: adding cloud-init to grml64-small as of today (2020-04-01) would require 14MB disk space.

**Comment by mika** [comment] 2020-06-03 14:18
FTR: we do ship cloud-init with grml-full nowadays and it's known to be working fine for some common use cases, like setting network configuration, SSH access key and hostname. To enable it on Grml, boot with boot option `services=cloud-init`. If you configured a SSH public, logging in as user `grml` works. For static network configuration you need to boot with boot options `nonetworking services=cloud-init,networking`. 

Closing hereby :)

**Closed by mika** 2020-06-03 14:18 UTC
Labels: feature-request, grml-release
