### ISSUE TITLE
grml-info not working on Grml 2018.12

### ISSUE THREAD

**Issue by mika** [grml/grml#134] opened 2019-06-14 13:39 UTC
When pressing `i` inside `grml-quickconfig` prompt, this should invoke `grml-info`, which is supposed to invoke `links2 -driver fb`, which actually segfaults.

**Comment by jaimet** [comment] 2019-06-15 08:41
mika, I have just discovered that my usb-stick was/is failing, and that is the cause of much of the strange behaviour that I have been observing using grml. I have now copied grml64-full_2018.12.iso to a new usb-stick, and grml-info is working perfectly (on a "bare metal" HP EliteBook 8560p). Consequently, I no longer need this issue to be open. I'll continue this conversation on the grml mailing list. Many thanks, Jaime

**Comment by mika** [comment] 2019-06-15 08:47
@jaimet thanks for information, but I managed to reproduce this issue as well, so we'll verify it once again before closing :)

**Comment by jkirk** [comment] 2020-05-20 16:07
I just tested `grml-info` with the current [Grml daily ISO](https://daily.grml.org/grml64-full_testing/2020-05-20_05-22-20/grml64-full_testing_build3124.iso) running in a VirtualBox 6.1. Works fine.

If this issues comes up again we need to investigate further. Closing for now.

**Closed by jkirk** 2020-05-20 16:07 UTC
Labels: bug, grml-release, verify
