### ISSUE TITLE
rclone completion

### ISSUE THREAD

**Issue by gaabster** [grml/grml#91] opened 2018-02-09 09:47 UTC
Hi.

I am not sure if this is an issue with grml-zsh, probably more like I don't know how to do. I can't seem to make rclone completion to work with grml-zsh on arch.

Rclone docs say to use `sudo rclone genautocomplete zsh` to generate the script in `/usr/share/zsh/vendor-completions/_rclone` :
```
#compdef rclone

_arguments \
  '1: :->level1' \
  '2: :->level2' \
  '3: :_files'
case $state in
  level1)
    case $words[1] in
      rclone)
        _arguments '1: :(authorize cachestats cat check cleanup config copy copyto cryptcheck cryptdecode dbhashsum dedupe delete genautocomplete gendocs help info listremotes ls ls2 lsd lsjson lsl md5sum memtest mkdir mount move moveto ncdu obscure purge rcat rmdir rmdirs serve sha1sum size sync touch tree version)'
      ;;
      *)
        _arguments '*: :_files'
      ;;
    esac
  ;;
  level2)
    case $words[2] in
      config)
        _arguments '2: :(create delete dump edit file password providers show update)'
      ;;
      genautocomplete)
        _arguments '2: :(bash zsh)'
      ;;
      serve)
        _arguments '2: :(http webdav)'
      ;;
      *)
        _arguments '*: :_files'
      ;;
    esac
  ;;
  *)
    _arguments '*: :_files'
  ;;
esac
```
Now, that part works, the file is created but there is still no completion when using zsh.

Any idea what to do?

Thanks in advance and have a good day everyone.

**Comment by ft** [comment] 2018-02-09 15:41
At a zsh command prompt, do:

```
print ${_comps[rclone]}
```

Tell me what that prints.

**Comment by gaabster** [comment] 2018-02-09 15:58
It prints nothing.

**Comment by ft** [comment] 2018-02-09 18:57
Okay. So we've confirmed, that your completion file is not registered with the completion system. The question is why. First thing I would look at is the path you're installing the file to. To that end, what does this print?

```
print -l $fpath
```

**Comment by gaabster** [comment] 2018-02-09 19:00
OK this is is what I get;

```
/usr/share/grml/zsh/functions
/usr/share/grml/zsh/completion
/usr/local/share/zsh/site-functions
/usr/share/zsh/site-functions
/usr/share/zsh/functions/Calendar
/usr/share/zsh/functions/Chpwd
/usr/share/zsh/functions/Completion
/usr/share/zsh/functions/Completion/Base
/usr/share/zsh/functions/Completion/Linux
/usr/share/zsh/functions/Completion/Unix
/usr/share/zsh/functions/Completion/X
/usr/share/zsh/functions/Completion/Zsh
/usr/share/zsh/functions/Exceptions
/usr/share/zsh/functions/Math
/usr/share/zsh/functions/MIME
/usr/share/zsh/functions/Misc
/usr/share/zsh/functions/Newuser
/usr/share/zsh/functions/Prompts
/usr/share/zsh/functions/TCP
/usr/share/zsh/functions/VCS_Info
/usr/share/zsh/functions/VCS_Info/Backends
/usr/share/zsh/functions/Zftp
/usr/share/zsh/functions/Zle
```

**Comment by ft** [comment] 2018-02-09 19:10
There you go. Your directory isn't in there.

The one you picked is something that Debian's zsh adds as a compile time option for other Debian packages to put their completion functions in. Other vendors likely don't have that one.

See http://zshwiki.org/home/config/functions and https://unix.stackexchange.com/questions/33255/how-to-define-and-load-your-own-shell-function-in-zsh for how zsh's function system works.

**Comment by gaabster** [comment] 2018-02-09 19:14
Oh nice, I got some reading to do. I'm pretty sure I should be ok now. 

Thank you very much for your help.

**Comment by ft** [comment] 2018-02-09 19:36
Okay, if you need further assistance, we're in #grml on freenode; or use our mailing lists: http://ml.grml.org/mailman/listinfo/grml

In any case, this is not a bug. Closing therefore.

**Closed by ft** 2018-02-09 19:36 UTC
