### ISSUE TITLE
EFI / Grub: error message in sub menu entry

### ISSUE THREAD

**Issue by jkirk** [grml/grml#214] opened 2024-12-18 16:08 UTC
**Describe the bug**
Booting Grml in EFI mode brings the new Grub  boot theme (see: grml/grml-live@b0b979e).
When selecting any sub menu entry under "Options" the following error is shown:

> "error: null src bitmap in grub_video_bitmap_create_scaled."

There is a "Press any key to continue..." prompt, but Grub continues after a few seconds.

**Steps To Reproduce**

Tested this in a Virtualbox VM with the "Enable EFI" option:

In Grub Boot Menu select "Options" >  any option.

**Expected behavior**

**Screenshots**
![VirtualBox_grml_18_12_2024_16_39_08](https://github.com/user-attachments/assets/36d2065a-dc5b-4dfd-ad21-b9f269219f92)

**In which Grml Version did the bug occur?**
`grml-full-daily20241218build160testing-amd64.iso`

Output of `grml-version`:
```sh
# grml-version
grml-full-amd64 d20241218b160 Release Codename daily20241218build160testing
```

**Additional context**

I found the following hints:

* [#922161](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=922161) grub2: null src bitmap error while trying to drop background image
* https://superuser.com/questions/1846090/in-grub2-what-does-error-null-src-bitmap-in-grub-video-bitmap-create-scaled

**Comment by mika** [comment] 2024-12-18 16:20
Duplicate of https://github.com/grml/grml-live/issues/209

**Closed** 2024-12-18 16:26 UTC
